version: "3"

services:
  webserver:
    build: .
    container_name: webserver
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    expose:
      - 5000
  
  nginx:
    build: ./services/nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - webserver